version: "3.4"

services:
  tomochain:
    build: ./
    image: tomochain/tomochain
    volumes:
      - "tomochain:/build/tomochain"
      - "./.pwd:/build/.pwd"
      - "/etc/localtime:/etc/localtime:ro"
    restart: "always"
    env_file: .env
    healthcheck:
      test: ["CMD", "bash", "/build/healthcheck.sh"]
      interval: 2m
    ports:
      - "30303:30303"
      - "8545:8545"

  netapis:
    build: ./netapis
    image: tomochain/netapis
    restart: "on-failure:10"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    env_file: .env
    depends_on:
      - tomochain 

  telegraf:
    image: telegraf:1.5
    hostname: ${INSTANCE_NAME}
    depends_on:
      - influxdb
    env_file: .env
    environment:
      - "HOST_PROC=/rootfs/proc"
      - "HOST_SYS=/rootfs/sys"
      - "HOST_ETC=/rootfs/etc"
      - "HTTP_RESPONSE_PROD_URL=https://api.replyblock.com/api/v1/config/get"
      - "HTTP_RESPONSE_DEV_URL=https://dev.replyblock.com/api/v1/config/get"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

volumes:
  influxdb:
  tomochain:
      name: tomochain
